version: "3.9"
services:
  app:
    build: ./job/
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: rodolfo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081